// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBQMJsNkmiAsGLdbAWQOjJ71t7AunbOH4',
    appId: '1:722889361340:web:cb5fcc7d847497a8b68db9',
    messagingSenderId: '722889361340',
    projectId: 'newnew-1a703',
    authDomain: 'newnew-1a703.firebaseapp.com',
    databaseURL: 'https://newnew-1a703-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'newnew-1a703.appspot.com',
    measurementId: 'G-K7GQK8WHF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_5gIci-gr_Ib8gu9b76e5tU2MUYZjMio',
    appId: '1:722889361340:android:bb2fb99223ba3c9cb68db9',
    messagingSenderId: '722889361340',
    projectId: 'newnew-1a703',
    databaseURL: 'https://newnew-1a703-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'newnew-1a703.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPxWi4kB0R7K0jpBMbHBNUCvfvPWIo7xo',
    appId: '1:722889361340:ios:e4cfed5a970af211b68db9',
    messagingSenderId: '722889361340',
    projectId: 'newnew-1a703',
    databaseURL: 'https://newnew-1a703-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'newnew-1a703.appspot.com',
    iosClientId: '722889361340-i5upkinikh265kavug4130fo6ai8mmp0.apps.googleusercontent.com',
    iosBundleId: 'com.saheli.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPxWi4kB0R7K0jpBMbHBNUCvfvPWIo7xo',
    appId: '1:722889361340:ios:383a5e95c323eab9b68db9',
    messagingSenderId: '722889361340',
    projectId: 'newnew-1a703',
    databaseURL: 'https://newnew-1a703-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'newnew-1a703.appspot.com',
    iosClientId: '722889361340-e06lm94sihlbsi074cji82h2mi6fa2tc.apps.googleusercontent.com',
    iosBundleId: 'com.example.saheliApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBQMJsNkmiAsGLdbAWQOjJ71t7AunbOH4',
    appId: '1:722889361340:web:09e0a8b5eeefc802b68db9',
    messagingSenderId: '722889361340',
    projectId: 'newnew-1a703',
    authDomain: 'newnew-1a703.firebaseapp.com',
    databaseURL: 'https://newnew-1a703-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'newnew-1a703.appspot.com',
    measurementId: 'G-P7CGZT5H4Y',
  );
}
